version: '3.5'

services:

    postgres:
        restart: always
        image: postgres:10
        volumes:
            - ./var/lib/postgres:/var/lib/postgresql/data/
        env_file:
            - ./var/etc/pgsql.env
        container_name: flaskintro_pg
        ports:
            - "5534:5432"

    redis:
        restart: always
        image: redis:5
        volumes:
            - ./var/lib/redis:/data
        container_name: flaskintro_rd
        ports:
            - "6481:6379"
